/*
 * 2026-07-30 실제 20분 57초 사냥 영상에서 추출한 44px 버프 아이콘 표본.
 * 야누스는 중앙 시간 숫자를, 익스트림 골드는 왼쪽 아래 숫자를 마스킹했다.
 */
(() => {
  const encodedTemplates = {
    janus: 'KwAYAAkA7QDmAO0AyAC3AMcAxwC9ALsAzADLANAAxgDJANIAtACwAK0ADQAIAAQATwBQAFQAOAA7AEIAqQCmALcAcwBtAIkAfAB3AI4AuACzAMkASQBEAFoAWABsAGsAPQBLAFYA////////////////////////////////////////////////NQA/AFoAPQBKAFoA////////////////////////////////////////////////MgA8AFUAPwBRAFMA////////////////////////////////////////////////NwBAAF0AOwBNAFEA////////////////////////////////////////////////MgA8AFUASABSAF4AQABHAGEAQgBLAGwAVABYAH0AUgBOAIEAQAA4AGkAWgBfAHMAMwA5AE8AQwBSAFcALwAzAEwANQA8AFgAdgB8AJwAgACHAKEAPABBAGEALgAxAFIAIwAoADwAAAAKAB4ArwC4AL0AtAC7AMsAtAC7AM0AtgC9AM8AugDBANMAvQDFANIAAAABABAAUQBaAGkANQA2AEoAcwB3AJQARgBLAGkASQBOAGwAdwB8AJoAMAA4AE8AQQBNAFsANgBGAGAA////////////////////////////////////////////////KQA3AFIANwBGAGUA////////////////////////////////////////////////NQBEAFcAPABMAGUA////////////////////////////////////////////////MgBAAFoAOgBPAGIA////////////////////////////////////////////////KgBBAFEAPwBLAGEAQgBOAGYATwBXAHsAUgBRAHsAUABNAHgAQwBHAGoASwBXAG8AMAA8AFYAOQBFAFMALwA4AFUAOQBFAF8AeACBAJ4AfACHAKcANAA/AFsAJwA5AE0AIQAsAEIAAAAFAB8AtADDANYArAC5AMoAtwC6AMsAtQC7AMsAtwDAAM8AtQDEAMkAAAAFABkAVABaAGgAMQA4AEsAYwBsAIsATgBRAHAAQgBCAGYAbAByAJYALgA6AFIAQgBKAGEAQQBJAF4A////////////////////////////////////////////////KgA3AFoAPwBHAFwA////////////////////////////////////////////////NAA+AFcAQwBNAFkA////////////////////////////////////////////////MwBAAFAASQBQAGAA////////////////////////////////////////////////MwAzAFcAQgBOAF4ARQBKAGoATABOAHQAUABQAIIAVABWAHwARgBJAHIAUQBZAGwAOQBAAFwAIAAxAEEAKwA3AE8ALwA4AFkAeQCFAJsAfQCKAJ0ANgBBAF8ALAA3AFMAEQAeAD4ACQAEAAgAxADDANUAsQC3AM0AyQDLANcA1ADYAOQA0wDVAOQA0QDRAN0ADwAIAAIAQgBKAF0ANQA7AFUAZQBoAIcASgBPAG8AVABVAHMAYwBnAIAAMQA4AEsASwBNAFwARABVAF8A////////////////////////////////////////////////OQBFAFMAPwBNAFYA////////////////////////////////////////////////NQA/AEsAQQBMAGIA////////////////////////////////////////////////OAA/AFIAPgBMAGYA////////////////////////////////////////////////KwA3AF0ASwBTAGoASABKAGEARQBKAHIAVgBXAIUAVABcAHMARQBMAGgASwBPAGgALwA1AFUAQQBEAFMALwA1AFUAOgBDAGQAeAB+AKAAgwCIAKYAOwBGAGIALQA4AE4AHAApADkA',
    janusEnding: 'AAAIACQAaABvAIkAZABsAH8AZwBvAIIAZwBvAIQAaQBxAIYAagB2AIYAAAAGABoATABcAHUAKwA1AFAAYgBrAIgAPgBIAGMAPwBIAGUAaQByAJEAMgA7AFgAPgBEAF4AOwBJAGYAXQBgAIEAZwBpAJIAYwBmAIkAYwBmAIkAbABvAJIAVgBcAH4ALQA9AFcAPgBMAGcATQBQAHMASwBNAHYAPgBBAGwAPwBCAG0ATwBQAH4AUgBYAHoAMQBBAFsAPQBMAGMAUABSAHkAQwBEAHIAPwBHAHUAQwBFAHUARQBGAHYAUQBXAHkAMQBBAFsAPQBRAGoAQwBGAGcATwBTAIAAPgBFAHMAPAA9AGsATABVAHwARgBQAHMAKwA/AFoAPgBPAGMARwBOAGoAQABIAGwATwBXAHwATQBSAHwAOQBGAGkAUABeAHsALgBAAFgANgBCAFAAMgA+AFQAOQBDAFwAewCCAJ4AdgCEAKEALwA/AFkALgA+AFcAJgA1AEoA',
    extremeGold: 'OQA6AEwAQAA7AFEAPQA5AFIAQABHAFcAMgA2AE8ALwA7AEsAMgA3AEsAPQBDAE8A3QDaAOMA0wDBALMAdgBuAD0AdAB6ADAAmQCBAFsA3QDJAMIA1QDcAOIAHQAjACMA1gDcANwA1ADFAKgA2wC9ADkArQBkABcAWwA+ABQA5ADGAL4A4ADfAOQAAAAAAAAA3gDcAN0A0AC5AJAAqwCrAGEAqwCFAEYApQCDAGoA4QDBAKwA4QDiAOYAAgAAAAUA0wDKAMEAzQC2AHMAngB2AFIAmgB1AEAAlABzAEAA0ACcAG0A5ADWANUAAAAEAAQA////////////////////////////////////////1wDAAI4A1wDMALAAAAAEAAAA////////////////////////////////////////WgBRAEoAeABxAHgAAAAHAAkA////////////////////////////////////////bQBlAFgAdwBxAHUAAAAEAA0APQA9AFcAOwAzAEsAQgA5AE4AOQA+AFQAKgA1AEcALQAzAFMALgAvAE0AQABAAFgA3QDbAOgA0wDDALQAfQBvAEAAfQB3ADkAiAB6AF0A2QDLAMIA2wDiAOoAGgAeACcA3wDeAOMA0gC8AKQAzwC4ADgAqABoAAcAYAA+ABAA4ADJALcA3wDlAOUAAAADAAIA3QDSAOIAywC2AIkAqQCoAFgAqACBAEgAogCOAFkA6QDDAKwA3ADhAN0AAAACAAUA1wDDALoA0QCyAIMAmgB6AEsAogB8AD4AnAB5AEMAxwCeAGYA3wDVAMsAAAABAAAA////////////////////////////////////////xQC5AIcA3gDVALYAAAAAAAIA////////////////////////////////////////NQA8AEIANABDAEgAwgDUANgA////////////////////////////////////////NgBKAFEAQABJAFAADgAbACEAAwAAAA4ACQABABgACgAFABsADQAEABkAAAABAA4AAAABABMADQAIAB4ARQBEAFQAOgA6AFIAPQA0AFMAOQA+AFsAMgBDAFcAKQA3AFQAJAA7AE0ASABKAF8AVwBZAGgAPQA/AFQARgBCAFkARABCAFoAPABBAFcAMgA6AE8AMQA5AE4AWgBeAGoAfAB9AIEAPQBBAFoAQgBCAFoAQgBCAFoAPQBCAFgALwA6AE4AMQA8AFAAYABlAGkAfwCDAIQAPQBCAFYAQgBCAFoAQgBBAGAAPABCAFgALgA8AEcAMwA6AEwAXwBkAGAAhQCFAIMA////////////////////////////////////////NwBEAFQAXgBjAFwAigCHAH4A////////////////////////////////////////FwAjAC8AHwAjACwAJQAjADAA////////////////////////////////////////KAA0AEAAMwA4AEsAOAA5AEsAAwAAABIAAAAAAAwAAAAAAA8AAAAAABIAAAACAAsAAAABABEADAALABkAQQA+AFEAPwA3AFwAQAA5AFsAPwA/AFkAOgBAAFoAKgA4AFIAJwA4AEwAQABCAFkAYwBfAHAAPABBAFQAQwBAAFUAQwBBAFcAOwBAAFQALgA5AEsAKAA4AEgAVwBeAGYAfAB9AIEAPgBFAFgAQQBDAFoAPgBCAFsAOwBBAFkALwA6AFAAKAA4AEcAXABkAGcAhACGAIMAPQBFAFwAPgBEAF4AOgBEAF8AOABCAF0ALgA6AFQAKAA4AEUAXABlAGQAhACHAH4A////////////////////////////////////////NQBDAFAAYABrAGUAggCKAH8A////////////////////////////////////////GgAkADAAIAAjACgAJwAmACwA////////////////////////////////////////KAAxAEAAMQA9AEkANQBBAFEA'
  };
  const movedGoldEncoded = 'QABDAFQAQgBBAFEAPwBBAE4APwBGAFAANgA/AEQAMQBCAEkAKgBFAFAALABBAFIA1wDXAOEA0ADKALQAegByAEMAeAB0ACsAnACDAG8A1wDGALwA1wDdAO0AFwAgACkA4QDcAOMA1ADCAKoAxAC0AC0ApwBlAAcAZgBFABIA5ADDALwA2wDaAOIAAgABAAkA2QDaANwAygDEAKAAoACdAGgAqgB6ACYArQCMAF8A4ADBAK0A3QDbAOAABQAAAAcAzwDCALEAvQCoAHkAuACBAFgArwB7AFMAnQB7AEsAwgCTAF8A3QDTANEAAgADAAUA////////////////////////////////////////wACyAIEA1wDGALIABAAAAAYA////////////////////////////////////////ZABWAFMAdgB4AHMAAAAAAAQA////////////////////////////////////////dwBqAGEAcgBxAG8AAAABAAYAOgA/AFIAOwBDAE4AOwBFAE4AOQBCAEsAPgBAAEwANgBCAFIAKwBDAE8ALABKAFQA2gDfAOIA1ADJALcAeQBzAFEAewB0ACMAmwB9AGEA3gDLAMQAzwDeAOUADQAbAB4A3gDiAOEA2QDIAKwAzQC5ADYAqQBnAAYAagBKABsA4QDKAMIA2QDaAN4AAAADAAUA3QDbANwAyQC2AI4ApQCoAGMArwB7ACgAsgCSAGEA4wC9AKgA3QDcAOQABQAEAAoA1ADFALIAzQC5AIcAsAB8AEwAtAB1AEIAlwB9AFoA1QCpAHoA3ADUAMkAAAADAAMA////////////////////////////////////////yAC7AIYAzQDBAKcAAAAHAAYA////////////////////////////////////////VgBNAFAAcwBzAH8AAAABAAYA////////////////////////////////////////bQBrAF4AcgByAHQAAAADAAgA';

  const decode = (encoded) => {
    const bytes = Uint8Array.from(atob(encoded), char => char.charCodeAt(0));
    const view = new DataView(bytes.buffer);
    const values = [];
    for (let offset = 0; offset < bytes.length; offset += 2) {
      values.push(view.getInt16(offset, true));
    }
    const templateLength = 8 * 8 * 3;
    const templates = [];
    for (let offset = 0; offset < values.length; offset += templateLength) {
      templates.push(values.slice(offset, offset + templateLength));
    }
    return templates;
  };

  window.BUFF_ICON_TEMPLATES.janusVariants.push(...decode(encodedTemplates.janus));
  window.BUFF_ICON_TEMPLATES.janusEndingVariants = decode(encodedTemplates.janusEnding);
  window.BUFF_ICON_TEMPLATES.extremeGoldVariants.push(
    ...decode(encodedTemplates.extremeGold).slice(0, 2),
    ...decode(movedGoldEncoded)
  );
})();
