'use strict';
const assert = require('node:assert/strict');
global.window = global;
global.addEventListener = () => {};
let enabled = true;
global.document = { getElementById: () => ({ checked: enabled }), createElement: () => ({ getContext: () => ({}) }) };
const alerts = [];
global.audioNotifier = { notify: (...args) => alerts.push(args) };
for (const name of ['버프인식기기준', '야누스인식기준', '익스트림골드인식기준', '영상학습인식기준', '거탐인식기기준', 'imageAnalyzer', '검출정확도개선', '룬검출정확도', '거탐검출정확도', '버프검출정확도', '야누스소멸감지']) require('../js/' + name + '.js');
let count = 0;
const tracker = new JanusPresenceTracker(() => count++);
const present = { present: true, canStart: true, match: { x: 10, y: 0, size: 33 } };
const absent = { present: false };
for (let t = 0; t < 3000; t += 450) tracker.update(absent, t);
assert.equal(count, 0, '처음부터 없으면 알리지 않음');
tracker.reset();
[0, 450, 900].forEach(t => tracker.update(present, t));
assert.equal(tracker.active, true);
[1350, 1800].forEach(t => tracker.update(absent, t));
tracker.update(present, 2250);
assert.equal(count, 0, '일시 가림 복구');
tracker.update({ present: true }, 2700);
assert.equal(count, 0, '회색 종료 위상은 존재로 취급');
[3150, 3600, 4050, 4500, 4950, 5400].forEach(t => tracker.update(absent, t));
assert.equal(count, 1, '소멸은 주기당 한 번');
[5850, 6300, 6750].forEach(t => tracker.update(present, t));
[7200, 7650, 8100, 8550].forEach(t => tracker.update(absent, t));
assert.equal(count, 2, '재사용 후 재알림');
tracker.reset();
[0, 450, 900].forEach(t => tracker.update(present, t));
tracker.update(absent, 5000);
[5450, 5900, 6350].forEach(t => tracker.update(absent, t));
assert.equal(count, 3, '분석 지연 뒤에도 이전 활성 상태를 보존하고 새 부재 1초를 확인');
tracker.reset();
[0, 450, 900].forEach(t => tracker.update(present, t));
tracker.update({ valid: false }, 1350);
[1800, 2250, 2700, 3150].forEach(t => tracker.update(absent, t));
assert.equal(count, 4, '검은 화면 중에는 알리지 않고 복귀 후 새 부재 1초로 확인');
// 실제 운영 어댑터: 판정 입력만 대체하고 상태/알림/회색 위상 경로는 그대로 실행.
const frame = { width: 66, height: 66, data: new Uint8ClampedArray(66 * 66 * 4).fill(100) };
let mode = 'active';
global.findJanusIcon = (_, previous, ending) => ({ found: mode === 'active' && !ending || mode === 'ending' && ending, x: 10, y: 0, size: 33 });
imageAnalyzer.measureBuffIconShape = () => ({ yellowDigitPixels: 10, largestYellowDigitComponent: 3 });
[0,450,900].forEach(t => imageAnalyzer.processJanusPresenceFrame(frame,t));
mode = 'ending';
[1350,1800,2250,2700].forEach(t => imageAnalyzer.processJanusPresenceFrame(frame,t));
assert.equal(alerts.length,0);
mode = 'absent';
[3150,3600,4050,4500,4950].forEach(t => imageAnalyzer.processJanusPresenceFrame(frame,t));
assert.equal(alerts.length,1);
assert.equal(alerts[0][1],'janus');
assert.equal(alerts[0][2].telegram,true);
mode = 'active';
[5400,5850,6300].forEach(t => imageAnalyzer.processJanusPresenceFrame(frame,t));
imageAnalyzer.reset();
assert.equal(imageAnalyzer.janusPresenceTracker.active,false);
console.log('야누스 상태·회색 위상·소멸·재사용·중단·텔레그램 요청 회귀 통과 (실제 전송은 모의 처리)');
let exactCount=0;
const exact=new JanusPresenceTracker(()=>exactCount++);
[0,300,600].forEach(t=>exact.update(present,t));
[900,1200,1500,1800,1899].forEach(t=>exact.update(absent,t));
assert.equal(exactCount,0,'부재 999ms에는 알리지 않음');
exact.update(absent,1900);
assert.equal(exactCount,1,'부재 1000ms에 알림');
console.log('1초 경계 검증 통과');
