'use strict';
const assert=require('node:assert/strict');
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../js');
const outputs=[];
const context={console,performance,atob,Uint8Array,Uint8ClampedArray,DataView,Map,Set,Date};
context.self=context;
context.addEventListener=()=>{};
context.postMessage=m=>outputs.push(m);
vm.createContext(context);
context.importScripts=(...files)=>files.forEach(f=>vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f}));
vm.runInContext(fs.readFileSync(path.join(root,'야누스분석워커.js'),'utf8'),context);
context.onmessage({data:{epoch:1,frame:{width:66,height:66,data:new Uint8ClampedArray(66*66*4)},now:0}});
assert.ok(outputs.some(m=>m.done&&m.epoch===1));
assert.equal(outputs.some(m=>m.alert||m.error),false);
context.onmessage({data:{epoch:2,reset:true}});
assert.equal(context.imageAnalyzer.janusPresenceTracker.active,false);
// 연결부: 작업 중 추가 요청 생략, 중지 뒤 오래된 알림 폐기.
global.window=global;
let callback,submitted=0,notified=0;
global.Worker=class{constructor(){callback=this;}postMessage(){submitted++;}terminate(){}};
global.document={getElementById:()=>({checked:true})};
global.screenCaptureManager={isStreaming:true};
global.audioNotifier={notify:()=>notified++};
global.imageAnalyzer={resetJanusPresence(){}};
require('../js/야누스워커연결.js');
const frame={data:new Uint8ClampedArray(4)};
imageAnalyzer.processJanusPresenceFrame(frame,0);
imageAnalyzer.processJanusPresenceFrame(frame,450);
assert.equal(submitted,1);
imageAnalyzer.resetJanusPresence();
callback.onmessage({data:{epoch:0,alert:{message:'stale',category:'janus'}}});
assert.equal(notified,0);
callback.onmessage({data:{epoch:0,done:true}});
imageAnalyzer.processJanusPresenceFrame(frame,900);
callback.onmessage({data:{epoch:1,alert:{message:'valid',category:'janus',options:{telegram:true}}}});
assert.equal(notified,1);
console.log('야누스 Worker 로드·프레임 처리·중복 요청 차단·중지 후 오래된 알림 폐기 통과');
